### ISSUE TITLE
Crash on launch | Windows 11

### ISSUE THREAD

**Issue by hungntv** [coltlv1994/RulesChanged#1]
OS: Windows 11
Crash on launch
Already install dotnet 6.0 and try everything I can
Crash log by Windows Event Viewer . Hope they're useful

```
Faulting application name: RulesChangedWPFNET.exe, version: 1.0.0.0, time stamp: 0x6216d00c
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3880, time stamp: 0xee1eae1c
Exception code: 0xe0434352
Fault offset: 0x0014a782
Faulting process id: 0x0x198C
Faulting application start time: 0x0x1DAE978DAC2711D
Faulting application path: D:\Games\RulesChanged_v1_2_2\RulesChangedWPFNET.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8830dea6-b072-4603-a6be-b11e402bf1ee
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: RulesChangedWPFNET.exe
CoreCLR Version: 6.0.3224.31407
.NET Version: 6.0.32
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'RulesChangedWPFNET.MainWindow' that matches the specified binding constraints threw an exception.' Line number '6' and line position '9'.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RulesChangedWPFNET.MainWindow.DEBUG_command_line_arguments() in C:\Users\Zhengyang Lyu\source\repos\RulesChangedWPFNET\RulesChangedWPFNET\MainWindow.xaml.cs:line 555
   at RulesChangedWPFNET.MainWindow..ctor() in C:\Users\Zhengyang Lyu\source\repos\RulesChangedWPFNET\RulesChangedWPFNET\MainWindow.xaml.cs:line 74
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at RulesChangedWPFNET.App.Main()
```

**Comment by Pablo-Zen** [comment]
That's such a coincidence.. I just ran into the same problem so I came to check out the Issue and found your post.
From the logs, you can tell it's an array out-of-bounds exception when parsing command line arguments. So, on a hunch, I tried running it with the -h flag, and It worked.
